apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: visuals
  name: grafana-deploy
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    env: visuals
  type: NodePort
status:
  loadBalancer: {}
