apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    env: monitor
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-prometh
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
      - targets:
    scrape_configs:
      - job_name: 'promt'
        static_configs:
        - targets: ['localhost:9090']
